version: '3'

services:
  # Interface de adminstração do MongoDB
  mongo-express:
    image: mongo-express
    ports:
      # porta de acesso 8081
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: intelivix
      ME_CONFIG_BASICAUTH_PASSWORD: Testeintelivix2020!
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: Testeintelivix2020!
    links:
      - mongo
    networks:
      - mongo-compose-network
    depends_on:
      - mongo
  # Docker Compose
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Testeintelivix2020!
    ports:
      # porta de acesso 27017
      - "27017:27017"
    volumes:
      - ./Volumes/MongoDB:/data/db
    networks:
      - mongo-compose-network

  postgresql:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Testeintelivix2020!"
    ports:
      - "15432:5432"
    volumes:
      - ./Volumes/MongoDB:PostgreSQL:/var/lib/postgresql/data
    networks:
      - postgres-compose-network

  pgadmin:
      image: dpage/pgadmin4
      environment:
        PGADMIN_DEFAULT_EMAIL: "fiorentinogiuseppebcc@gmail.com"
        PGADMIN_DEFAULT_PASSWORD: "Testeintelivix2020!"
      ports:
        - "16543:80"
      depends_on:
        - postgresql
      networks:
        - postgres-compose-network
networks:
    mongo-compose-network:
      driver: bridge
    postgres-compose-network:
      driver: bridge
